import logging
from datetime import datetime, timezone
from pathlib import Path

import duckdb


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATABASE_PATH = PROJECT_ROOT / "db" / "optimization_lab.duckdb"
QUERY_DIR = PROJECT_ROOT / "queries"
OUTPUT_DIR = PROJECT_ROOT / "output"
EXPLAIN_ANALYSIS_FILE = OUTPUT_DIR / "explain_analysis.md"


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def parse_named_queries(sql_text: str) -> list[tuple[str, str]]:
    queries = []
    current_name = None
    current_lines = []

    for line in sql_text.splitlines():
        stripped = line.strip()
        if stripped.startswith("-- name:"):
            if current_name and current_lines:
                queries.append((current_name, "\n".join(current_lines).strip().rstrip(";")))
            current_name = stripped.replace("-- name:", "", 1).strip()
            current_lines = []
        else:
            current_lines.append(line)

    if current_name and current_lines:
        queries.append((current_name, "\n".join(current_lines).strip().rstrip(";")))

    if not queries:
        raise ValueError("No named queries found")
    return queries


def read_query_file(path: Path) -> list[tuple[str, str]]:
    return parse_named_queries(path.read_text(encoding="utf-8"))


def plan_to_text(rows: list[tuple]) -> str:
    plan_parts = []
    for row in rows:
        if len(row) == 1:
            plan_parts.append(str(row[0]))
        else:
            plan_parts.append(" | ".join(str(value) for value in row))
    return "\n".join(plan_parts)


def detected_operations(plan_text: str) -> list[str]:
    checks = [
        ("Seq Scan", ["SEQ_SCAN", "SEQUENTIAL SCAN"]),
        ("Index Scan", ["INDEX_SCAN", "INDEX SCAN"]),
        ("Hash Join", ["HASH_JOIN", "HASH JOIN"]),
        ("Nested Loop", ["NESTED_LOOP", "NESTED LOOP"]),
        ("CTE", ["CTE"]),
        ("Aggregate", ["AGGREGATE", "GROUP_BY", "HASH_GROUP_BY"]),
        ("Filter", ["FILTER"]),
        ("Order By", ["ORDER_BY", "ORDER BY"]),
        ("Projection", ["PROJECTION"]),
    ]
    upper_plan = plan_text.upper()
    found = []
    for label, tokens in checks:
        if any(token in upper_plan for token in tokens):
            found.append(label)
    return found


def interpret_plan(query_name: str, query_type: str, operations: list[str]) -> str:
    if not operations:
        return "DuckDB did not expose one of the tracked operation labels in this plan."

    notes = []
    if "Seq Scan" in operations:
        notes.append("The plan scans table data sequentially, which can be acceptable for analytical scans but expensive when the filter is selective.")
    if "Index Scan" in operations:
        notes.append("The plan shows index usage for at least one access path.")
    if "Hash Join" in operations:
        notes.append("The plan uses a hash join, a common strategy for equality joins.")
    if "Nested Loop" in operations:
        notes.append("The plan shows a nested loop operation, which should be reviewed when row counts are high.")
    if "Aggregate" in operations:
        notes.append("The plan includes aggregation work.")
    if "CTE" in operations:
        notes.append("The query includes a CTE or DuckDB exposes a CTE step in the plan.")
    if "Filter" in operations:
        notes.append("The plan exposes filtering logic.")

    if query_type == "optimized" and "preaggregated" in query_name:
        notes.append("This optimized query reads a preaggregated table instead of recomputing metrics from transaction_logs.")

    return " ".join(notes)


def explain_query(connection: duckdb.DuckDBPyConnection, query_sql: str) -> str:
    rows = connection.execute(f"EXPLAIN ANALYZE {query_sql}").fetchall()
    return plan_to_text(rows)


def apply_indexes(connection: duckdb.DuckDBPyConnection) -> None:
    index_sql = (QUERY_DIR / "02_indexes.sql").read_text(encoding="utf-8")
    connection.execute(index_sql)


def run_explain_analysis() -> dict:
    if not DATABASE_PATH.exists():
        raise FileNotFoundError(f"DuckDB database not found: {DATABASE_PATH}")

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    baseline_queries = read_query_file(QUERY_DIR / "01_slow_queries.sql")
    optimized_queries = read_query_file(QUERY_DIR / "03_optimized_queries.sql")
    started_at = utc_now()
    query_summaries = []
    markdown_sections = [
        "# EXPLAIN Analysis",
        "",
        "This document is generated by `app/run_explain_analysis.py`.",
        "It records DuckDB `EXPLAIN ANALYZE` output for baseline and optimized queries.",
        "",
    ]

    with duckdb.connect(str(DATABASE_PATH)) as connection:
        for query_type, named_queries in [
            ("baseline", baseline_queries),
            ("optimized", optimized_queries),
        ]:
            if query_type == "optimized":
                apply_indexes(connection)

            for query_name, query_sql in named_queries:
                plan_text = explain_query(connection, query_sql)
                operations = detected_operations(plan_text)
                interpretation = interpret_plan(query_name, query_type, operations)
                query_summaries.append(
                    {
                        "query_name": query_name,
                        "query_type": query_type,
                        "operations": operations,
                    }
                )

                markdown_sections.extend(
                    [
                        f"## {query_name}",
                        "",
                        f"- query_type: `{query_type}`",
                        f"- relevant_operations: `{', '.join(operations) if operations else 'not detected'}`",
                        f"- interpretation: {interpretation}",
                        "",
                        "```text",
                        plan_text,
                        "```",
                        "",
                    ]
                )

    EXPLAIN_ANALYSIS_FILE.write_text("\n".join(markdown_sections), encoding="utf-8")
    return {
        "final_status": "PASSED",
        "started_at": started_at,
        "finished_at": utc_now(),
        "baseline_query_count": len(baseline_queries),
        "optimized_query_count": len(optimized_queries),
        "queries": query_summaries,
        "generated_paths": {
            "explain_analysis": str(EXPLAIN_ANALYSIS_FILE),
        },
    }


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)s | %(message)s")
    summary = run_explain_analysis()
    logging.info("EXPLAIN analysis generated: %s", summary["generated_paths"])


if __name__ == "__main__":
    main()
